---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-service
  name: email-service
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: email-service
  type: ClusterIP
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: saikrishnaoduru/yogendarr:email-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        
...
