---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
   app: project
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql
...
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: saikrishnaoduru/yogendarr:mysql
        
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 'Password'
          - name: MYSQL_PASSWORD
            value: 'root'
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
...
