---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  type: NodePort
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: eureka-server
        image: saikrishnaoduru/yogendarr:rabbitmq
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "root"
        - name: RABBITMQ_DEFAULT_PASS
          value: "root123"
...
